server:
  build: .

  command: make example

  volumes:
    - .:/usr/src/app

  ports:
   - "80:8080"

  environment:
    CINCH_URL_BUCKET: urls.cinchpolls-dev.com
    CINCH_URL_DOMAIN: http://nft.bz

  env_file:
    - cinch-secrets
